version: "3.7"

services:

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgresql_catalogue
    env_file: 
      - database_compose.conf

  catalogue:
    restart: always
    build: .
    container_name: imagecatalogue
    ports:
      - "5001:5001"
    env_file: 
      - database_compose.conf
    depends_on:
      - postgres

  uploads:
    restart: always
    build: ../ImageUpload/
    container_name: imageupload
    ports:
      - "5000:5000"
    env_file: 
      - ../upload_compose.conf
    depends_on:
      - catalogue
