apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2020-01-13T15:35:04Z"
  generation: 18
  labels:
    app: image-catalogue
  name: image-catalogue
  namespace: default
  resourceVersion: "2302459"
  selfLink: /apis/apps/v1/namespaces/default/deployments/image-catalogue
  uid: 454edd1c-361a-11ea-8554-42010a84003c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: image-catalogue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: image-catalogue
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: image-catalogue-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: image-catalogue-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: image-catalogue-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: image-catalogue-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: image-catalogue-config
        - name: POSTGRES_INITIALIZE
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_INITIALIZE
              name: image-catalogue-config
        image: registry.hub.docker.com/slosquad42/image_catalogue:latest
        imagePullPolicy: Always
        name: image-catalogue
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-13T15:35:04Z"
    lastUpdateTime: "2020-01-13T16:03:07Z"
    message: ReplicaSet "image-catalogue-74496d885c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-20T00:59:12Z"
    lastUpdateTime: "2020-01-20T00:59:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
